apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-blog.fullname" . }}
  labels:
    {{- include "api-blog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-blog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-blog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-blog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.ports }}
          - containerPort: {{ .value }}
            name: {{ .name }}
          {{- end }}
          # livenessProbe:
          #   initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
          #   httpGet:
          #     port: {{ .Values.liveness.port }}
          #     path: {{ .Values.liveness.path }}
          #   failureThreshold: {{ .Values.liveness.failureThreshold }}
          #   successThreshold: {{ .Values.liveness.successThreshold }}
          #   timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
          #   periodSeconds: {{ .Values.liveness.periodSeconds }}
          # readinessProbe:
          #   initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
          #   httpGet:
          #     port: {{ .Values.readiness.port }}
          #     path: {{ .Values.readiness.path }}
          #   failureThreshold: {{ .Values.readiness.failureThreshold }}
          #   successThreshold: {{ .Values.readiness.successThreshold }}
          #   timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}
          #   periodSeconds: {{ .Values.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.extraEnvVarsConfigMap .Values.extraEnvVarsSecret }}
          envFrom:
          {{- if or .Values.extraEnvVarsConfigMap }}
          - configMapRef:
              name: {{ .Values.extraEnvVarsConfigMap }}
          {{- end }}
          {{- if or .Values.extraEnvVarsSecret }}
          - secretRef:
              name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
