apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-blog.fullname" . }}
  labels:
    {{- include "api-blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.ports }}
  - port: {{ .value }}
    name: {{ .name }}
  {{- end }}
  selector:
    {{- include "api-blog.selectorLabels" . | nindent 4 }}
