global:
        scrape_interval: 5s
        evaluation_interval: 5s
alerting:
rule_files:
scrape_configs:
        - job_name: api
          static_configs:
                  - targets: ['api:3001']
        - job_name: api-blog
          static_configs:
                  - targets: ['api-blog:8080']
        - job_name: prometheus
          static_configs:
                  - targets: ['prometheus:9090']
        - job_name: postgres-exporter
          static_configs:
                  - targets: ['postgres-exporter:9187']
