apiVersion: v1
kind: PersistentVolume
metadata:
        name: postgresql-pv
        namespace: database
spec:
        storageClassName: manual
        capacity:
                storage: 10Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: postgresql-pvc
        namespace: database
spec:
        storageClassName: manual
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 10Gi
