name: CI workflows
on:
        push:
                tags:
                        - v*
                branches:
                        - main
        pull_request:
                branches:
                        - dev
                        - main

jobs:
        build-test-node:
                runs-on: ubuntu-latest

                strategy:
                        matrix:
                                node-version: [16.x]

                steps:
                        - name: Checkout
                          uses: actions/checkout@v2

                        - name: Install pnpm
                          uses: pnpm/action-setup@v2
                          with:
                                  version: 7.8.0

                        - name: Use Node.js ${{ matrix.node-version }}
                          uses: actions/setup-node@v2
                          with:
                                  node-version: ${{ matrix.node-version }}
                                  cache: 'pnpm'
                        - name: ci, build and test
                          run: |
                                  yarn global add pnpm
                                  pnpm i --frozen-lockfile
                                  npx playwright install --with-deps
                                  pnpm lint
                                  pnpm t
