name: golangci-lint
on:
        push:
                tags:
                        - v*
                branches:
                        - main
        pull_request:
permissions:
        contents: read

jobs:
        golangci:
                name: lint
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/setup-go@v3
                          with:
                                  go-version: 1.17
                        - uses: actions/checkout@v3
                        - name: Generate swagger docs
                          run: |
                                  cd apps/api
                                  go install github.com/swaggo/swag/cmd/swag
                                  /home/runner/go/bin/swag init
                        - name: golangci-lint
                          uses: golangci/golangci-lint-action@v3
                          with:
                                  version: v1.50.1
                                  working-directory: apps/api

                        - name: Test
                          run: |
                                  cd apps/api
                                  go test -v ./...
