name: Preview deploy
on:
        pull_request:
                branches:
                        - dev

jobs:
        deploy-preview:
                runs-on: ubuntu-latest

                steps:
                        - name: Checkout
                          uses: actions/checkout@v2

                        - name: Context
                          uses: okteto/context@latest
                          with:
                                  token: '${{ secrets.OKTETO_TOKEN }}'

                        - name: Deploy the preview environment
                          uses: okteto/deploy-preview@latest
                          env:
                                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                          with:
                                  name: pr-${{ github.event.number }}-nomorechokedboy
