name: Preview deploy
on:
        workflow_run:
                workflows:
                        ['Publish api', 'Publish api-blog', 'Publish noisy-boi']
                branches: [dev]
                types:
                        - completed
        pull_request:
                branches:
                        - dev
                paths:
                        - apps/api/**
                        - apps/api-blog/**
                        - apps/noisy-boi/**
                        - docker-compose.yml
                        - .dockerignore
                        - Cargo.lock
                        - Cargo.toml
                        - deploy/**
jobs:
        deploy-preview:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Context
                          uses: okteto/context@latest
                          with:
                                  token: '${{ secrets.OKTETO_TOKEN }}'
                        - name: Deploy the preview environment
                          uses: okteto/deploy-preview@latest
                          env:
                                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
                          with:
                                  name: pr-${{ github.event.number }}-nomorechokedboy
                                  timeout: 30m
