grafana:
        enabled: true
        adminPassword: 'admin'
        persistence:
                enabled: true
                accessModes: ['ReadWriteOnce']
                size: 1Gi
        service:
                type: LoadBalancer
prometheus:
        service:
                type: LoadBalancer
        prometheusSpec:
                serviceMonitorSelectorNilUsesHelmValues: false
